@node Applications and Flipper, Bugs, Usage, Top
@chapter Applications and Flipper

@menu
* Common MySQL error messages::  
@end menu

@node Common MySQL error messages,  , Applications and Flipper, Applications and Flipper
@section Common MySQL error messages

In a typical Flipper-based multi-master system, there are a few error messages which any client should be able to handle in order to provide a "seamless" experience for users, despite failover occurring.  During any failover using Flipper (and indeed other systems based on a similar model) the following errors must be handled:

@table @samp
@item @code{ERROR 1290 (HY000): The MySQL server is running with the --read-only option so it cannot execute this statement}
After the active master has been set read-only using @code{SET GLOBAL read_only=1}, any client which tries to run a new data-changing statement will receive this error.
@item @code{ERROR 2006 (HY000): MySQL server has gone away}
If the failover process occurs while a connection is idle, or if the connection is killed by the @code{Quiesce::KillAll} module, this error will be received on the next attempt to run a query.
@end table

If you choose to use the @code{Quiesce::KillAll} module to kill off connected users before a failover, you must handle two additional errors:

@table @samp
@item @code{ERROR 2013 (HY000): Lost connection to MySQL server during query}
If a connection is killing while it is currently running a query, the query will be aborted, and this error will be generated by the client.
@item @code{ERROR 1040 (00000): Too many connections}
If a connection attempt is made during the quiesce process, while @code{max_connections} is set to not allow new connections.
@end table

In nearly all cases, the best action to take would be to disconnect (if the connection is not already dropped), pause, reconnect, and retry.
