\input texinfo @c -*- texinfo -*-
@setfilename flipper.texi
@settitle Flipper Manual

@copying
Copyright @copyright{} 2007-2008 Proven Scaling.
@end copying

@titlepage
@title Flipper
@subtitle A system for managing MySQL replicating master-master pairs
@author Mike Griffiths and others

@page
@vskip 0pt plus 1filll
@insertcopying
@end titlepage

@syncodeindex fn cp
@synindex pg cp

@node Top, Overview, (dir), (dir)
@top flipper

@menu
* Overview::                    
* Installation::                
* Quick Start::                 
* Configuration::               
* Usage::                       
* Bugs::                        
* Future Developments::         
* Platform Notes::              
* Configuration Reference::     
* Credits::                     
* Contacting Proven Scaling::   
* Index::                       @detailmenu





@detailmenu
 --- The Detailed Node Listing ---

Installation

* Obtaining Flipper::           
* Installing Flipper from svn::  

Obtaining Flipper

* Packages::                    
* Source Code::                 

Installing Flipper from svn

* Where's perl?::               
* Copying files::               

Copying files

* Copying the script to your PATH::  
* Installing into your home directory or other arbitary location::  

Quick Start

* Before you begin::            
* Quick Start Installation::    
* Metadata::                    
* Pointing Flipper at the Metadata::  
* Quick Start Configuration::   
* Set up IP addresses::         
* Using Flipper::               

Configuration

* IP address information::      
* ARP sending command::         
* MySQL authentication::        
* SSH authentication::          
* Check configuration::         

Configuration

* Metadata Storage::            
* Metadata Access::             
* Configuration Variables::     
* Masterpair and Node names::   
* Network configuration::       
* SSH and sudo configuration::  
* MySQL configuration::         

Metadata Storage

* DBI metadata storage::        

Metadata Access

* Data Source Naming Scheme::   
* Authentication::              
* Pointing Flipper at Metadata::  

Network configuration

* IP address configuration::    
* Interface configuration::     

IP address configuration

* Node IP addresses::           
* Read and Write IP addresses::  
* Netmask and Broadcast addresses::  

SSH and sudo configuration

* ssh and sudo security::       

SSH and sudo Security

* Restricting sudo usage::      
* Restricting ssh access::      

Usage

* Command Line::                
* Commands::                    

Commands

* Displaying configuration - the config command::  
* Displaying the status of a masterpair - the status command::  
* Moving an IP to a node - the set command::  
* Swapping IPs from one node to the other - the swap command::  
* Moving IPs away from a node - the disable command::  
* Handling a failed node - the fail command::  

Bugs

* Known Bugs::                  

Platform Notes

* Linux::                       
* HP-UX::                       
* Unsupported Platforms::       

ARP announcements

* RHEL/CentOS::                 
* Debian::                      

Configuration Reference

* ip configuration variable::   
* ssh_ip configuration variable::  
* write_ip configuration variable::  
* read_ip configuration variable::  
* netmask configuration variable::  
* broadcast configuration variable::  
* path_to_ifconfig configuration variable::  
* ssh_user configuration variable::  
* use_sudo configuration variable::  
* mysql_user configuration variable::  
* mysql_password configuration variable::  
* mysql_port configuration variable::  
* interface configuration variable::  
* send_arp_command configuration variable::  

@end detailmenu
@end menu

@include flipper-overview.texi
@include flipper-installation.texi
@include flipper-quickstart.texi
@include flipper-configuration.texi
@include flipper-usage.texi
@include flipper-bugs.texi
@include flipper-future.texi
@include flipper-platform.texi
@include flipper-configuration-reference.texi
@include flipper-credits.texi
@include flipper-contact.texi
@include flipper-index.texi

@bye
