@node Installation, Configuration, Quick Start, Top
@chapter Installation
@cindex installation

@menu
* Obtaining Flipper::           
* Installing Flipper from svn::  
@end menu

@node Obtaining Flipper, Installing Flipper from svn, Installation, Installation
@section Obtaining Flipper

@menu
* Packages::                    
* Source Code::                 
@end menu

@node Packages, Source Code, Obtaining Flipper, Obtaining Flipper
@subsection Packages
@cindex installation, using binary packages
@cindex rpm, packages of Flipper

Pre-built packages for flipper can be downloaded from @uref{http://mirror.provenscaling.com/extras/provenscaling/}.  If a package is not available for your operating environment, then don't fear - it's very easy to download the source code and install it.

@node Source Code,  , Packages, Obtaining Flipper
@subsection Source Code
@cindex installation, from Subversion
@cindex svn, source repository for Flipper

To fetch the most recent stable version of Flipper from Subversion, simply run the following command in a shell:

@example
$ @b{svn checkout svn://svn.provenscaling.com/public/flipper/trunk/ flipper}
A    flipper/sql
A    flipper/sql/metadata.sql
A    flipper/flipper
A    flipper/doc
A    flipper/doc/flipper-future.texi
A    flipper/doc/flipper-quickstart.texi
A    flipper/doc/flipper-bugs.texi
A    flipper/doc/flipper-installation.texi
A    flipper/doc/flipper.texi
A    flipper/doc/flipper-configuration-reference.texi
A    flipper/doc/flipper-platform.texi
A    flipper/doc/flipper-usage.texi
A    flipper/doc/flipper-overview.texi
A    flipper/doc/flipper-configuration.texi
A    flipper/lib
A    flipper/lib/Flipper
A    flipper/lib/Flipper/Metadata
A    flipper/lib/Flipper/Metadata/Dummy.pm
A    flipper/lib/Flipper/Metadata/DBI.pm
A    flipper/lib/Flipper/Metadata.pm
Checked out revision 94.
$
@end example

If you want to check Flipper out to a different directory, specify something other than @samp{flipper} as the second parameter to @command{svn checkout}.

@node Installing Flipper from svn,  , Obtaining Flipper, Installation
@section Installing Flipper from svn

@menu
* Where's perl?::               
* Copying files::               
@end menu

@node Where's perl?, Copying files, Installing Flipper from svn, Installing Flipper from svn
@subsection Where's perl?

The flipper script assumes @file{perl} will be in @file{/usr/bin}.  If your Perl executable is located somewhere else, either change the @code{#!} line in the @file{flipper} script, or better still put a symlink in place in @file{/usr/bin/perl} to your perl binary, as there are plenty of other scripts out there which rely on perl being in @file{/usr/bin}.

@node Copying files,  , Where's perl?, Installing Flipper from svn
@subsection Copying files

You can either copy the @file{flipper} script to somewhere in your @env{PATH} and the perl modules into @@INC, or simply run the @file{flipper} script from any directory (usually your home directory), invoke it as @command{./flipper} and copy the perl modules into the same directory.

@menu
* Copying the script to your PATH::  
* Installing into your home directory or other arbitary location::  
@end menu

@node Copying the script to your PATH, Installing into your home directory or other arbitary location, Copying files, Copying files
@subsubsection Copying the script to your PATH
@cindex installation, manually copying files

You will almost definitely need super-user privileges to do this.

The @file{flipper} script can be copied to @file{/usr/bin}, @file{/usr/local/bin} or some other directory in your @env{PATH}.

Copy the @file{lib/Flipper} directory from subversion to some place in perl's @code{@@INC} on your system.  To list the directories in @code{@@INC} on your system, run @command{perl -e 'print join "\n",@@INC'}.

@file{/usr/lib/perl5/site_perl}, @file{/usr/local/lib/perl5/site_perl} on Linux/Solaris/BSD and @file{/Library/Perl} on Mac OS X are good places to put the @file{Flipper} directory.

@node Installing into your home directory or other arbitary location,  , Copying the script to your PATH, Copying files
@subsubsection Installing into your home directory or other arbitary location
@cindex installation, into home directory

The @file{flipper} script can run anywhere, so you can copy it to your home directory or other arbitary location.  This can be useful if you want to install Flipper on a node on which you don't have super-user privileges.

If you do this, and you're only going to ever invoke Flipper as @command{./flipper}, you can copy the @file{lib/Flipper} directory from subversion to the same directory as the @file{flipper} script.  This works by virtue of the current working directory always appearing in @code{@@INC}.

If you're on Mac OS X with a case insensitive filesystem, you won't be able to put the @file{Flipper} subdirectory and the @file{flipper} script in the same directory.  The workaround is to put the @file{Flipper} directory into @file{/Library/Perl}, as superuser privileges shouldn't be required for that.

