TEXINFO_MAIN = flipper.texi

TEXINFO_SOURCES = \
	flipper-overview.texi \
	flipper-quickstart.texi \
	flipper-installation.texi \
	flipper-configuration.texi \
	flipper-usage.texi \
	flipper-applications.texi \
	flipper-bugs.texi \
	flipper-future.texi \
	flipper-platform.texi \
	flipper-configuration-reference.texi \
	flipper-credits.texi \
	$(NULL)

IMAGE_DIRS=\
  illustrations \
  $(NULL)

GRAFFLE_SOURCES=\
	illustrations/architecture.graffle \
	illustrations/architecture-a.graffle \
	illustrations/architecture-b.graffle \
	illustrations/commands/status.graffle \
	# this illustration crashes omnigraffle on export for some reason
	#illustrations/commands/swap-set-fail-disable.graffle \
	$(NULL)

include support/docs-formats.make