#!/usr/bin/perl -w

# Copyright (c) 2007-2008, Proven Scaling LLC
# 
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
# 
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
# 
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

use strict;
use Sys::Syslog;

openlog('flippersh', '', '');

my $command = 'shell';
if (scalar @ARGV > 0 && $ARGV[0] eq '-c')
{
  $command = $ARGV[1];
}

if ($command =~ m%uname -s;(?:/sbin/|/usr/sbin/)?ifconfig -a$%
  or $command =~ m%sudo (?:/sbin/|/usr/sbin/)?ifconfig [^;]+$%
  or $command =~ m%sudo (?:/sbin|/usr/sbin/)?arping [^;]+$%)
{
  syslog('info', "Allowing command: $command");
  closelog();
  exec "sh", "-c", $command;
}

syslog('info', "Refusing command: $command");
closelog();
die "You can't do that.\n";
